# Name of your workflow
name: Basic CI Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the master branch
  push:
    branches: [ master ]
  # Also allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Step 3: Runs a multi-line script
      - name: Run a multi-line script
        run: |
          echo This is the first line.
          echo This is the second line.
