name: Basic CI Workflow

on:
  push:
     branches: [ master ]
  workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
        -name: Checkout code
         uses: actions/checkout@v4

        -name: Run a one-line script
         run: echo Hello, world!

        -name: Run a multi-line script
         run: 
           echo This is the first line.
           echo This is the second line.
